### ISSUE TITLE
[Windows] The generator doesn't generate message in a test scenario?

### ISSUE THREAD

**Issue by ph** [logstash-plugins/logstash-input-generator#3]
Found this issue in the specs for the file output and s3 output.
It may be a problem with the specs but they are running on macos/linux.

```
1) LogStash::Outputs::File ship lots of events to a file agent(C:/Users/Adm
strator/logstash/vendor/bundle/jruby/1.9/gems/logstash-output-file-0.1.3/spec
tputs/file_spec.rb:30:in) runs
     Failure/Error: block.call
     Insist::Failure:
       Expected 10101, but got 0
     # C:\Users\Administrator\logstash\lib\logstash\runner.rb:57:in `run'
     # C:\Users\Administrator\logstash\lib\logstash\runner.rb:112:in `run'
     # C:\Users\Administrator\logstash\lib\logstash\runner.rb:170:in `run'
```

``` ruby
    tmp_file = Tempfile.new('logstash-spec-output-file')
    event_count = 10000 + rand(500)

    config <<-CONFIG
    input {
      generator {
        message => "hello world"
        count => #{event_count}
        type => "generator"
      }
    }
    output {
      file {
        path => "#{tmp_file.path}"
      }
    }
    CONFIG

    agent do
      line_num = 0

      # Now check all events for order and correctness.
      tmp_file.each_line do |line|
        event = LogStash::Event.new(LogStash::Json.load(line))
        insist {event["message"]} == "hello world"
        insist {event["sequence"]} == line_num
        line_num += 1
      end

      insist {line_num} == event_count
    end # agent
  end
```

**Comment by ph** [comment]
https://github.com/elasticsearch/logstash/issues/2487

**Comment by ph** [comment]
using `Socket.gethostname.force_encoding(Encoding::UTF_8)` in the generator makes the file_spec passes.
